- name: add root postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    login_port: "{{database_port}}"
    role_attr_flags: CREATEDB,SUPERUSER
    password: "{{database_password}}"
  tags: debug

- postgresql_db:
    name: root
    login_user: root
    login_port: "{{database_port}}"
    owner: root
  name: Create the a database for root
